### PR TITLE
User information

### PR DESCRIPTION
**Pull request by GabbyGenereux**
The user information side of the project is at a good state where it can be reviewed by others, then hopefully merged into master. Current functionality to expect:

Add new user into the database
Get list of all users currently in the database

### CODE REVIEW

**Comment by xlirate** [comment]
There are no tests at all, and there are no database constraints.

Also, if a field is AutoGenerated, we do not ever set it with our code.

**Comment by xlirate** [comment]
This is still not ready. It needs tests.

**Comment by xlirate** [comment]
This needs to be looked over and merged.

Can at least 2 of you three look at it?

**Comment by GabbyGenereux** [comment]
My goal was to have someone else write the tests for it, to maximaize the involvement of others.

I think it would have been smart for you to create a new pull request, on a new branch, titled with the feature you decided you wanted to implement. However, I will review this tonight and get back to you.

**Comment by GabbyGenereux** [comment]
Did a simple test and it crashed. Please review the items before you push them next time. 

Current error occurs on /allusers, cannot access userID.

Please fix before it can be merged.

**Comment by xlirate** [comment]
That has been fixed. It was a simple rename issue. The field is now just called id.

**Comment by GabbyGenereux** [comment]
Pulled and tested, merging.

**Pull request merged**
